### ISSUE TITLE
Load balancing: round-robin vs sticky sessions

### ISSUE THREAD

**Issue by alecberney** [nicrausaz/RES-2021-HTTP-Infrastructure#7]
You do a setup to demonstrate the notion of sticky session.
You prove that your load balancer can distribute HTTP requests in a round-robin fashion to the dynamic server nodes (because there is no state).
You prove that your load balancer can handle sticky sessions when forwarding HTTP requests to the static server nodes.
You have documented your configuration and your validation procedure in your report.

**Comment by nicrausaz** [comment]
Todo: Add documentation & tests

**Comment by nicrausaz** [comment]
Documentation & tests have been merged
